### ISSUE TITLE
https://deno.land/std/prettier/vendor/parser_typescript.js is broken

### ISSUE THREAD

**Issue by kt3k** [denoland/registry#115]
- The url https://deno.land/std/prettier/vendor/parser_typescript.js responses with 502 (curl) or 503 (browser) statuses.

This file has the huge size (2.3M). I guess some of the resource limits of Lambda were hit during processing this request. cf. https://docs.aws.amazon.com/lambda/latest/dg/limits.html 
I think we need to increase the limits of some of the resources.

**Comment by bartlomieju** [comment]
CI started failing in main repo because of this issue

CC @ry

**Comment by ry** [comment]
@kt3k @bartlomieju Thanks for the notice. I believe it's indeed caused by [Lambda@Edge response limits](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html#limits-lambda-at-edge). The docs state that "Size of a response that is generated by a Lambda function, including headers and body" must be less than 1MB for Origin request and response events.

I've added a fallback to redirects in the case of large files in #116 ... It's not very pretty but I think it fixes the problem. It's already been deployed.

**Comment by kt3k** [comment]
@ry Thank you for the fix! 😄 now `deno fmt` works normally!
